<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Category;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    function delete($id) {
        $em = $this->getEntityManager();
        $delete = $this->findOneById($id);

        $em->remove($delete);
        $em->flush();
    }
}
