<?php

namespace AppBundle\Repository;

/**
 * User7Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class User7Repository extends \Doctrine\ORM\EntityRepository
{
}
